### ISSUE TITLE
Result display of local IRIs should not add brackets

### ISSUE THREAD

**Issue by mkroetzsch** [knowsys/nemo-web#2]
Nemo treats plain constants as local IRIs, but normally tries to avoid brackets in such cases (also in CSV output etc). Howeve,r the web version will add such brackets, which might confuse new users (who are trying the web version first). Example:

```
r(a,b).
@output r.
```

This will show a result row `<a> <b>` for `r`. Since Nemo Web shows `"` around all strings, there is no danger of confusion if we simply omit `<>` in all IRIs, for the display. The CSV export should just use Nemo's CSV formatting and not make own formatting decisions there.

**Comment by monsterkrampe** [comment]
This should be fixed now, i.e. iris are not wrapped in `<>` anymore.
