### ISSUE TITLE
Add outputs if missing

### ISSUE THREAD

**Issue by mkroetzsch** [knowsys/nemo-web#3]
Nemo web currently only shows output predicates that are declared explicitly. It is good to let the user control this, but if no outputs are given at all, then this is not meaningful (future versions of Nemo will optimize by output and would not do anything in this case). A good default would be to have outputs for all predicates (EDB and IDB) in this case.

Code on how to add default outputs can be found in the Rust client's main method. What we want here is similar to the option `--export all` in the client, but only in cases where no outputs/exports are defined.

**Comment by monsterkrampe** [comment]
When no outputs are defined, we output all predicates by default. There was some handling implemented for this but it needed some fixing to get it working.
