### ISSUE TITLE
Online and Offline Tracing mismatch

### ISSUE THREAD

**Issue by aannleax** [knowsys/nemo-web#5]
For this code example:

```
r(a,b) .
p(?X,!V) :- r(?X,?Y) .
q(?X,STR(?Y)) :- p(?X,?Y) .
rs(STR(?X),STR(?Y)) :- r(?X, ?Y) .

@output r.
@output p.
@output q.
@output rs.
```

Tracing `r(a,b)` works but `rs("a","b")` doesn't. However this is possible through the command line. Also tracing `rs("a","b")` makes it so that the outputs are no longer displayed. Instead it shows "Loading...". At this point, the tracing stops working entirely.

**Comment by monsterkrampe** [comment]
This is mistake in the Petgraph Creation for Evonne within Nemo tracing.
The ASCII tracing works as expected.
[Nemo Web Next](https://tools.iccl.inf.tu-dresden.de/nemo/next/) offers both tracing options.
